dist: trusty
sudo: required # this is necessary to get gcc-4.8 for some reason (otherwise gcc-4.6 is used)
language: python
python:
  - 2.7
  - 3.3
  - 3.5
install: pip install -r requirements.txt
script: make test
