# Adapted from https://github.com/bsmurphy/PyKrige/blob/master/appveyor.yml
build: false

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda-x64
    - PYTHON_VERSION: 3.4
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "cd C:\\projects\\simhash-py"
  # create a conda virtual environement
  - "conda create -n simhash-env --yes python=%PYTHON_VERSION%"
  - activate simhash-env
  - pip install -r requirements.txt
  - git submodule update --init --recursive
  - python setup.py install



test_script:
  - activate simhash-env # activate the virtualenv
  - python setup.py build_ext --inplace
  - SET PYTHONHASHSEED=0
  - nosetests --verbose --nocapture
